.PHONY: clean All

All:
	@echo "----------Building project:[ Matrices - Debug ]----------"
	@cd "Matrices" && "$(MAKE)" -f  "Matrices.mk"
clean:
	@echo "----------Cleaning project:[ Matrices - Debug ]----------"
	@cd "Matrices" && "$(MAKE)" -f  "Matrices.mk" clean
